# -*- coding: utf-8 -*-
"""[이한샘]N개의 최소공배수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YvqSqz3qBp2e_32zQeWb9KvwAS1vy5X4
"""

def solution(arr):
    for i in range(len(arr)):
      if i < len(arr)-1:
        x,y= arr[i], arr[i+1]
        a,b=x,y
        while b!= 0 :
          a,b = b, a%b
          arr[i],arr[i+1]=x, x*y//a
    return arr[-1]

from fractions import gcd


def nlcm(num):      
    answer = num[0]
    for n in num:
        answer = n * answer / gcd(n, answer)

    return answer

# 아래는 테스트로 출력해 보기 위한 코드입니다.
print(nlcm([2,6,8,14]));