# -*- coding: utf-8 -*-
"""[이한샘]신규아이디추천.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YvqSqz3qBp2e_32zQeWb9KvwAS1vy5X4
"""

import re

def solution(new_id):
    new_id = new_id.lower()
    new_id = re.sub("[^0-9a-zA-Z._-]","", new_id)

    newid_list = list(new_id)
    for i in range(len(newid_list)) :
      if i != len(newid_list)-1:
        if newid_list[i]=='.' and newid_list[i+1] =='.':
          newid_list[i] = '!'
    new_id = ''.join(newid_list)
    new_id = new_id.replace('!','')

    if new_id[0] == '.':
      new_id = new_id[1:]

    if not new_id :
      new_id = 'a'

    if len(new_id) >=16 :
      new_id = new_id[:15]

    if new_id[-1] == '.':
      new_id = new_id[:-1]
      
    if len(new_id) <= 2:
      while len(new_id) <3 :
        new_id += new_id[-1]

    
    return new_id