# -*- coding: utf-8 -*-
"""[이한샘]콜라스추측.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1se-LSpAymEPn1gEAuXgKLNasyWNbyLxu
"""

def solution(num):
    count = 0
    while num != 1:
      if num%2 ==0 :
        num = num/2
        count +=1
      else : 
        num = num*3+1
        count +=1
      if count >= 500 :
        return -1
    return count

solution(6)