# -*- coding: utf-8 -*-
"""[이한샘]구명보트.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YvqSqz3qBp2e_32zQeWb9KvwAS1vy5X4
"""

def solution(people, limit):
    people = sorted(people)
    count = 0
    i=0
    j=len(people)-1
    while i <=j: # 초기 i는 제일 적은 몸무게, j는 제일 큰 몸무게
      count += 1
      if people[i] + people[j] <= limit: 
        i += 1 # i에 1을 더하는 것은 추가된 보트에 적은 몸무게를 같이 태운다
      j -= 1 # 큰 몸무게는 무조건 탄다 
    return count

people = [70, 80, 50]
limit = 100

people = sorted(people)
count = 0
i=0
j=len(people)-1
while i <=j: # 초기 i는 제일 적은 몸무게, j는 제일 큰 몸무게
  count += 1
  if people[i] + people[j] <= limit: 
    i += 1 # i에 1을 더하는 것은 추가된 보트에 적은 몸무게를 같이 태운다
  j -= 1 # 큰 몸무게는 무조건 탄다 
count