# -*- coding: utf-8 -*-
"""[이한샘]행렬의곱셈.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kw4Q7eY0Mb0AXxVJtpoeFjjbBNPYJk6s
"""

def solution(arr1, arr2):
    answer = [[]]
    return answer

arr1 = [[1, 4], [3, 2], [4, 1]]
arr2 = [[3, 3], [3, 3]]

answer = [[0 for _ in range(len(arr2[0]))] for _ in range(len(arr1))]
answer

for i in range(len(arr1)) :
  for j in range(len(arr2[0])):
    for x in range(len(arr1[0])):
        answer[i][j] += arr1[i][x] *arr2[x][j]
answer