# -*- coding: utf-8 -*-
"""[이한샘]이상한문자.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1se-LSpAymEPn1gEAuXgKLNasyWNbyLxu
"""

def solution(s):
    s_list = s.split(" ")
    answer =[]
    for string in s_list :
      for i in range(len(string)) :
        if i%2 == 0 :
          answer.append(string[i].upper())
        else :
          answer.append(string[i].lower())
      answer.append(' ')
    return  ''.join(answer[:-1])

s="i am a boy"

solution(s)