# -*- coding: utf-8 -*-
"""[이한샘] 짝수와홀수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RloXNM7HBrNf1GRXTWUoTz_HhCyCCoPi
"""

def solution(num):
    if num % 2 == 0 :
      return 'Even'
    else :
      return 'Odd'