# -*- coding: utf-8 -*-
"""[이한샘]정수내림차순.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PMfD_vl3FjgjNqCS7pMSDY1sAg2Z_oEK
"""

def solution(n):
    return int(''.join(sorted(list(str(n)), reverse=True)))