# -*- coding: utf-8 -*-
"""[이한샘]숫자의표현.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YvqSqz3qBp2e_32zQeWb9KvwAS1vy5X4
"""

def solution(n):
    count = 0
    for i in range(1, n+1) :
      sum = 0
      for j in range(i, n+1):
        sum += j
        if sum == n :
          count += 1
          break
        elif sum > n :
          break
    return count