# -*- coding: utf-8 -*-
"""[이한샘]폰켓몬.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k6ArUVnRjXN6AUjyBBLPyMiPw0gxKZ0U
"""

def solution(nums):
    
    if len(nums)/2 > len(set(nums)) :
      return len(set(nums))
    else :
      return len(nums)/2

solution([3,3,3,2,2,4])