# -*- coding: utf-8 -*-
"""[이한샘]올바른괄호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k6ArUVnRjXN6AUjyBBLPyMiPw0gxKZ0U
"""

def solution(s):
    if s.count('(') != s.count(')') :
      return False
    elif s.startswith(')') or s.endswith('('):
      return False
    else :
      if '()' in s :
        s = s.replace('()','')
        if s.startswith(')') or s.endswith('('):
          return False
        else :
          return True

# 좋은 답변

def is_pair(s):
    # 함수를 완성하세요
    x = 0
    for w in s:
        if x < 0:
            break
        x = x+1 if w=="(" else x-1 if w==")" else x
    return x==0


# 아래는 테스트로 출력해 보기 위한 코드입니다.
print( is_pair("(hello)()"))
print( is_pair(")("))