# -*- coding: utf-8 -*-
"""[이한샘] 음양더하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BGBQR3BSE3qDHqURAIEcklgtvRNKH95u
"""

def solution(absolutes, signs):
    sum = 0
    for i in range(len(absolutes)) :
      if signs[i] == False :
        absolutes[i] *= -1
      sum += absolutes[i]
    return sum