# -*- coding: utf-8 -*-
"""[이한샘] 다트게임.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HUBVVEFWc-vUyNzy99Kckdqk5qZphq5H
"""

def solution(dartResult):
    score = []
    n = ''
    for i in dartResult:
        if i.isdecimal():
            n += i
        elif i == 'S':
            score.append(int(n) ** 1)
            n = ''
        elif i == 'D':
            score.append(int(n) ** 2)
            n = ''
        elif i == 'T':
            score.append(int(n) ** 3)
            n = ''
        elif i == '*':
            if len(score) > 1:
                score[-2] *= 2
            score[-1] *= 2
        elif i == '#':
            score[-1] *= -1
    answer = sum(score)
    #print(answer)
    return answer

dartResult = '1D#2S*3S'

solution(dartResult)