# -*- coding: utf-8 -*-
"""[이한샘] 내적.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BGBQR3BSE3qDHqURAIEcklgtvRNKH95u
"""

def solution(a, b):
    dot_sum = 0

    for i,j in zip(a,b) :
        dot_sum += i*j
    return dot_sum