# -*- coding: utf-8 -*-
"""[이한샘]3진법.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PMfD_vl3FjgjNqCS7pMSDY1sAg2Z_oEK
"""

def solution(n):
    if n ==1 :
      return 1
    string=""
    while n/3 >= 3 :
      string += str(n%3)
      n=int(n/3)
    string += str(n%3)
    string += str(int(n/3))
    answer = 0
    for i,s in enumerate(string[::-1]) :
      answer += int(s)*(3**i)
    return answer

n = 1

solution(n)

string=""
while n/3 > 3 :
  string += str(n%3)
  print(string)
  n=int(n/3)
string += str(n%3)
string += str(int(n/3))
string

answer = 0
for i,s in enumerate(string[::-1]) :
  answer += int(s)*(3**i)
  print(answer)
answer

3**4