# -*- coding: utf-8 -*-
"""[이한샘]3진법.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PMfD_vl3FjgjNqCS7pMSDY1sAg2Z_oEK
"""

def solution(n):
    string=""
    while n:
      string += str(n%3)
      n= n//3
    answer = 0
    for i,s in enumerate(string[::-1]) :
      answer += int(s)*(3**i)
    return answer

# 좋은 풀이

def solution(n):
    tmp = ''
    while n:
        tmp += str(n % 3)
        n = n // 3
    print(tmp)
    answer = int(tmp, 3)
    return answer