# -*- coding: utf-8 -*-
"""[이한샘]실패율.ynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kw4Q7eY0Mb0AXxVJtpoeFjjbBNPYJk6s
"""

def solution(N, stages):
    answer = []
    pre_num = 0
    set_list = list(set(stages))
    rate = {}

    if N+1 in set_list:
      set_list.remove(N+1)
    for s in set_list:
      #print(s, stages.count(s)/(len(stages)-pre_num))
      rate[s] = stages.count(s)/(len(stages)-pre_num)
      pre_num += stages.count(s)
    for i in range(1, N+1) :
        if i not in set_list:
          rate[i] = 0
    for x,y in sorted(rate.items(), key=lambda x : x[1], reverse=True):
      answer.append(x)
    return answer

# 좋은 답안

def solution(N, stages):
    result = {}
    denominator = len(stages)
    for stage in range(1, N+1):
        if denominator != 0:
            count = stages.count(stage)
            result[stage] = count / denominator
            denominator -= count
        else:
            result[stage] = 0
    return sorted(result, key=lambda x : result[x], reverse=True)