# -*- coding: utf-8 -*-
"""[이한샘]시저암호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PMfD_vl3FjgjNqCS7pMSDY1sAg2Z_oEK
"""

def solution(s, n):
    answer = ""

    for char in s :
      if char == ' ':
        answer += " "
      elif ord(char) <=90 :
        answer += chr(((ord(char)+n-ord('A'))%26)+65)
      else :
        answer += chr(((ord(char)+n-ord('a'))%26)+97)
    return answer