# -*- coding: utf-8 -*-
"""[이한샘]문자열내림차순.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PMfD_vl3FjgjNqCS7pMSDY1sAg2Z_oEK
"""

def solution(s):
    return ''.join(sorted(list(s), reverse=True))