# -*- coding: utf-8 -*-
"""[이한샘]별찍기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1se-LSpAymEPn1gEAuXgKLNasyWNbyLxu
"""

a, b = map(int, input().strip().split(' '))

a=5
b=3

for b in range(b) :
  print(a*'*')