# -*- coding: utf-8 -*-
"""[이한샘] 핸드폰번호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RloXNM7HBrNf1GRXTWUoTz_HhCyCCoPi
"""

def solution(phone_number):
    return phone_number.replace(phone_number[:-4],"*"*len(phone_number[:-4]))