# -*- coding: utf-8 -*-
"""[이한샘]소수찾기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nZ2ZV_x9lL5h-GlirdxmBRY4BSTLIn4F
"""

from itertools import permutations

def solution(numbers):
    temp=[]
    for i in range(1, len(numbers)+1):
      num = list(permutations(numbers, i))
      for n in num:
        result = ""
        n = list(n)
        for i in n :
          result += i
        temp.append(result)
    combis = list(set(map(int, temp)))
    if 0 in combis :
      combis.remove(0)
    if 1 in combis:
      combis.remove(1)
    count = 0
    final = []
    for c in combis :
      is_deci = True
      for i in range(2, int(c**0.5)+1):
        if c%i == 0 :
          is_deci = False
          break
      if is_deci :
        count += 1
    return count