# -*- coding: utf-8 -*-
"""[이한샘]최댓값과최솟값.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nZ2ZV_x9lL5h-GlirdxmBRY4BSTLIn4F
"""

def solution(s):
    max_num = int(s.split(" ")[0])
    min_num = int(s.split(" ")[0])
    for s in s.split(" "):
      if int(s)>max_num :
        max_num = int(s)
      if int(s)<min_num :
        min_num = int(s)
    
    return f"{min_num} {max_num}"

# 좋은 답안

def solution(s):
    s = list(map(int,s.split()))
    return str(min(s)) + " " + str(max(s))