# -*- coding: utf-8 -*-
"""[이한샘]jadencase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-TkY_wd3mn2RkxuWL6lT0gLnVR2ggByA
"""

def solution(s):
    return " ".join(list(map(lambda x : x.capitalize(),s.split(" "))))