# -*- coding: utf-8 -*-
"""[이한샘]문자열내마음대로.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hd0OiM7yHpXmhddhncXmpuXvgbZwH51-
"""

def solution(strings, n):
    temp = []
    answer=[]
    for s in string:
      temp.append(s[n]+s)
        
    for t in sorted(temp) :
      answer.append(t[1:])

    return answer

# 좋은 답안
def solution(strings, n):
  return sorted(strings, key=lambda x: x[n])