# -*- coding: utf-8 -*-
"""[이한샘] 하샤드.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RloXNM7HBrNf1GRXTWUoTz_HhCyCCoPi
"""

def solution(x):
    sum = 0
    for s in str(x):
      sum += int(s)

    if x%sum ==0 :
      return True
    else : 
      return False