# -*- coding: utf-8 -*-
"""[이한샘]피보나치.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kw4Q7eY0Mb0AXxVJtpoeFjjbBNPYJk6s
"""

def solution(num):
    f_1,f_2 = 0,1
    for i in range(num):
        f_1,f_2 = f_2,f_1+f_2
    return f_1%1234567