# -*- coding: utf-8 -*-
"""[이한샘] x만큼 간격이....ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RloXNM7HBrNf1GRXTWUoTz_HhCyCCoPi
"""

def solution(x, n):
    answer = []
    for i in range(n) :
      answer.append(x+x*i)
    return answer

x=2
n=5

px+x*i